/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ali.gltf 
Author: tipatat (https://sketchfab.com/tipatat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/muhammad-ali-tilt-brush-vr-painting-tribute-9d9c3c4739924e14b20c727075123e42
Title: Muhammad Ali Tilt Brush VR Painting Tribute
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Ali = (props) => {
  const { nodes, materials } = useGLTF('/ali.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.All_Marker__0.geometry}
          material={materials.RootNode}
        />
        <mesh
          geometry={nodes.All_Marker__0_1.geometry}
          material={materials.RootNode}
        />
        <mesh
          geometry={nodes.All_Marker__0_2.geometry}
          material={materials.RootNode}
        />
        <mesh
          geometry={nodes.All_Marker__0_3.geometry}
          material={materials.RootNode}
        />
        <mesh
          geometry={nodes.All_Highlighter__0.geometry}
          material={materials.RootNode}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/ali.gltf');

export default Ali;
