/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 archer.gltf 
Author: DivyeSh PanchAl (https://sketchfab.com/DivyeSh.PanchAl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cult-member-enemy-character-0de7496d24ff4bef81a6937005ce34c1
Title: Cult Member (Enemy Character)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Archer = (props) => {
  const { nodes, materials } = useGLTF('/archer.gltf');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.cl_1_low_CM_Base_Mat1_0.geometry}
          material={materials.CM_Base_Mat1}
          position={[-0.021, 19.125, 4.662]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.881}
        />
        <mesh
          geometry={nodes.Collar_low_CM_Base_Mat1_0.geometry}
          material={materials.CM_Base_Mat1}
          position={[78.263, 22.656, -1.804]}
          scale={0.783}
        />
        <mesh
          geometry={nodes.CF_Pants_low_CM_Base_Mat1_0.geometry}
          material={materials.CM_Base_Mat1}
          position={[0, -4.727, 1.503]}
          scale={1.879}
        />
        <mesh
          geometry={nodes.Cloth_Pieces_low_CM_Base_Mat1_0.geometry}
          material={materials.CM_Base_Mat1}
        />
        <mesh
          geometry={nodes.Hood_low_CM_Base_Mat1_0.geometry}
          material={materials.CM_Base_Mat1}
          position={[78.263, 22.656, -40.943]}
          scale={0.783}
        />
        <mesh
          geometry={nodes.Belt_Cloth_low_CM_Base_Mat1_0.geometry}
          material={materials.CM_Base_Mat1}
          position={[0.39, 0, -50.202]}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Belt_2_low_CM_Base_Mat2_0.geometry}
          material={materials.CM_Base_Mat2}
        />
        <mesh
          geometry={nodes.CF_Shoes_low_CM_Base_Mat2_0.geometry}
          material={materials.CM_Base_Mat2}
        />
        <mesh
          geometry={nodes.Body_belt_low_CM_Base_Mat2_0.geometry}
          material={materials.CM_Base_Mat2}
          position={[90.084, 7.015, -46.889]}
          scale={0.868}
        />
        <mesh
          geometry={nodes.cl_3_low_CM_Base_Mat2_0.geometry}
          material={materials.CM_Base_Mat2}
          position={[0, 0, 7.863]}
          scale={21.694}
        />
        <mesh
          geometry={nodes.Belt_Leather_low_CM_Base_Mat2_0.geometry}
          material={materials.CM_Base_Mat2}
          position={[-0.008, -7.356, -54.899]}
          scale={[0.944, 1.011, 1.035]}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.inner_eye_low_CM_eyes_0.geometry}
          material={materials.CM_eyes}
        />
        <mesh
          geometry={nodes.outer_eye_low_CM_eyes_0.geometry}
          material={materials.CM_eyes}
          position={[-50, 0, 0]}
        />
      </group>
      <group
        position={[0.197, 0.22, -0.319]}
        rotation={[-2.843, -0.812, 3.089]}
        scale={0.008}
      >
        <group position={[-9.656, 2.254, 2.634]} scale={1.192}>
          <mesh
            geometry={nodes.CF_Q_Arrows4_CF_Q_Arrows_Mat_0.geometry}
            material={materials.CF_Q_Arrows_Mat}
            position={[-36.458, -7.06, -193.231]}
            rotation={[-0.511, 0.108, -1.065]}
          />
          <mesh
            geometry={nodes.CF_Q_Arrows2_CF_Q_Arrows_Mat_0.geometry}
            material={materials.CF_Q_Arrows_Mat}
            position={[41.467, -28.128, 6.149]}
            rotation={[-0.541, 0.169, -1.009]}
          />
          <mesh
            geometry={nodes.CF_Q_Arrows5_CF_Q_Arrows_Mat_0.geometry}
            material={materials.CF_Q_Arrows_Mat}
            position={[107.567, -6.903, -6.937]}
            rotation={[-1.131, 0.628, -0.2]}
          />
          <mesh
            geometry={nodes.CF_Q_Arrows1_CF_Q_Arrows_Mat_0.geometry}
            material={materials.CF_Q_Arrows_Mat}
            position={[12.988, -30.435, -19.054]}
            rotation={[-0.781, 0.462, -0.647]}
          />
          <mesh
            geometry={nodes.CF_Q_Arrows3_CF_Q_Arrows_Mat_0.geometry}
            material={materials.CF_Q_Arrows_Mat}
            position={[-32.644, -107.599, 280.296]}
            rotation={[-0.815, 0.488, -0.601]}
          />
        </group>
        <mesh
          geometry={nodes.CF_Quiver_CF_Q_Arrows_Mat_0.geometry}
          material={materials.CF_Q_Arrows_Mat}
        />
        <mesh
          geometry={nodes.CF_Q_Arrows_CF_Q_Arrows_Mat_0.geometry}
          material={materials.CF_Q_Arrows_Mat}
        />
        <mesh
          geometry={nodes.CF_Q_Arrows6_CF_Q_Arrows_Mat_0.geometry}
          material={materials.CF_Q_Arrows_Mat}
          position={[137.073, 292.389, -172.189]}
          rotation={[-2.536, -1.222, 1.486]}
          scale={1.355}
        />
      </group>
      <group
        position={[0.013, 0.884, 0.775]}
        rotation={[Math.PI / 2, -1.346, 1.531]}
        scale={0.011}
      >
        <mesh
          geometry={nodes.Bow_CM_Bow_Mat_0.geometry}
          material={materials.CM_Bow_Mat}
        />
        <mesh
          geometry={nodes.String_CM_Bow_Mat_0.geometry}
          material={materials.CM_Bow_Mat}
          position={[0.169, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.CFbody_low_CM_Base_Body_0.geometry}
        material={materials.CM_Base_Body}
        position={[0, 0, 0.042]}
        scale={0.018}
      />
      <mesh
        geometry={nodes.pPlane1_Floor_mat_0.geometry}
        material={materials.Floor_mat}
        scale={0.01}
      />
    </group>
  );
};

useGLTF.preload('/archer.gltf');

export default Archer;
