/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asteroid.glb 
Author: 007ajay (https://sketchfab.com/007ajay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lo-poly-metroid-meteor-e66f9b1c4817430da6af666f9c70bc9f
Title: Lo Poly metroid | Meteor
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Asteroid = (props) => {
  const { nodes, materials } = useGLTF('/asteroid.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
          position={[1.36, 1.058, -0.245]}
          rotation={[0.05, 0.044, -0.852]}
          scale={2.263}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material_2}
          position={[0.176, -0.15, -0.273]}
          rotation={[0.071, -0.696, 1.89]}
          scale={0.617}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/asteroid.glb');
export default Asteroid;
