/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asteroid.gltf 
Author: 007ajay (https://sketchfab.com/007ajay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lo-poly-metroid-meteor-e66f9b1c4817430da6af666f9c70bc9f
Title: Lo Poly metroid | Meteor
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Asteroid = (props) => {
  const { nodes, materials } = useGLTF('/asteroid.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group
          position={[0.181, -0.149, -0.271]}
          rotation={[0.071, -0.696, 1.89]}
          scale={1.473}
        >
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.material_1}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials.material_2}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.material_2}
          />
        </group>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
          position={[1.239, 0.93, -0.096]}
          rotation={[0.05, 0.044, -0.852]}
          scale={1.049}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/asteroid.gltf');

export default Asteroid;
