/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car.gltf 
Author: KraftKatStudio (https://sketchfab.com/KraftKatStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-car-58c5285a35f9434daa3ec82d3872aebf
Title: flying car
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

const Car = (props) => {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/car.gltf');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group
                  name="Torus001_1"
                  position={[-1.95, 1.444, 2.179]}
                  rotation={[-0.721, 0.387, 0.321]}
                  scale={0.536}
                >
                  <mesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group
                  name="Torus002_12"
                  position={[2.045, 1.397, 2.122]}
                  rotation={[-0.721, 0.387, 0.321]}
                  scale={0.536}
                >
                  <mesh
                    name="Object_43"
                    geometry={nodes.Object_43.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_44"
                    geometry={nodes.Object_44.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group
                  name="Torus003_13"
                  position={[-1.944, 1.456, -2.197]}
                  rotation={[-0.721, 0.387, 0.321]}
                  scale={0.536}
                >
                  <mesh
                    name="Object_46"
                    geometry={nodes.Object_46.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_47"
                    geometry={nodes.Object_47.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group
                  name="Torus004_14"
                  position={[2.071, 1.434, -2.168]}
                  rotation={[-0.721, 0.387, 0.321]}
                  scale={0.536}
                >
                  <mesh
                    name="Object_49"
                    geometry={nodes.Object_49.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_50"
                    geometry={nodes.Object_50.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group name="Cube_0" position={[0, 2.217, 0]}>
                  <mesh
                    name="Object_4"
                    geometry={nodes.Object_4.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Object_5"
                    geometry={nodes.Object_5.geometry}
                    material={materials['Material.014']}
                  />
                  <mesh
                    name="Object_6"
                    geometry={nodes.Object_6.geometry}
                    material={materials['Material.015']}
                  />
                  <mesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.006']}
                  />
                  <mesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials['Material.004']}
                  />
                  <mesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Cylinder_2"
                  position={[-2.015, 1.465, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.245, 1.482, 0.245]}
                >
                  <mesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Sphere_3"
                  position={[-2.017, 1.464, 2.099]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.362}
                >
                  <mesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Cylinder001_4"
                  position={[2.044, 1.465, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.245, 1.482, 0.245]}
                >
                  <mesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Sphere001_5"
                  position={[2.013, 1.464, 2.099]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.362}
                >
                  <mesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Cylinder002_6"
                  position={[3.159, 3.105, 3.58]}
                  rotation={[0.038, 0.285, -1.705]}
                  scale={[0.609, 0.786, 0.609]}
                >
                  <mesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Cube001_7"
                  position={[0.298, 2.669, 0]}
                  scale={[0.484, 0.484, 0.564]}
                >
                  <mesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    material={materials['Material.003']}
                  />
                  <mesh
                    name="Object_28"
                    geometry={nodes.Object_28.geometry}
                    material={materials['Material.014']}
                  />
                  <mesh
                    name="Object_29"
                    geometry={nodes.Object_29.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Cylinder003_8"
                  position={[2.794, 3.15, 3.675]}
                  rotation={[0, 0.339, -Math.PI / 2]}
                  scale={0.286}
                >
                  <mesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_32"
                    geometry={nodes.Object_32.geometry}
                    material={materials['Material.002']}
                  />
                  <mesh
                    name="Object_33"
                    geometry={nodes.Object_33.geometry}
                    material={materials['Material.004']}
                  />
                </group>
                <group
                  name="Cube002_9"
                  position={[-2.374, 2.865, -0.026]}
                  rotation={[0, 0, 0.506]}
                  scale={0.513}
                >
                  <mesh
                    name="Object_35"
                    geometry={nodes.Object_35.geometry}
                    material={materials['Material.002']}
                  />
                </group>
                <group
                  name="Cylinder004_10"
                  position={[0, 1.542, 1.93]}
                  rotation={[0, 0, -1.203]}
                  scale={0.266}
                >
                  <mesh
                    name="Object_37"
                    geometry={nodes.Object_37.geometry}
                    material={materials['Material.003']}
                  />
                  <mesh
                    name="Object_38"
                    geometry={nodes.Object_38.geometry}
                    material={materials['Material.003']}
                  />
                  <mesh
                    name="Object_39"
                    geometry={nodes.Object_39.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Cylinder005_11"
                  position={[-1.436, 2.459, 0.049]}
                  rotation={[0.23, 0.142, -1.027]}
                  scale={0.285}
                >
                  <mesh
                    name="Object_41"
                    geometry={nodes.Object_41.geometry}
                    material={materials['Material.002']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/car.gltf');

export default Car;
