/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car.glb 
Author: KraftKatStudio (https://sketchfab.com/KraftKatStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-car-58c5285a35f9434daa3ec82d3872aebf
Title: flying car
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

const Car = (props) => {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/car.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group name="GLTF_SceneRootNode">
            <group
              name="Torus001_1"
              position={[-1.95, 1.444, 2.179]}
              rotation={[-0.721, 0.387, 0.321]}
              scale={0.536}
            >
              <mesh
                name="Object_14"
                geometry={nodes.Object_14.geometry}
                material={materials.PaletteMaterial001}
                position={[-0.041, -0.543, 0.007]}
                scale={1.216}
              />
              <mesh
                name="Object_15"
                geometry={nodes.Object_15.geometry}
                material={materials.PaletteMaterial004}
                position={[-0.041, -1.946, 0.007]}
                scale={0.954}
              />
            </group>
            <group
              name="Torus002_12"
              position={[2.045, 1.397, 2.122]}
              rotation={[-0.721, 0.387, 0.321]}
              scale={0.536}
            >
              <mesh
                name="Object_43"
                geometry={nodes.Object_43.geometry}
                material={materials.PaletteMaterial001}
                position={[-0.092, -0.544, 0.069]}
                scale={1.216}
              />
              <mesh
                name="Object_44"
                geometry={nodes.Object_44.geometry}
                material={materials.PaletteMaterial004}
                position={[-0.092, -1.947, 0.069]}
                scale={0.954}
              />
            </group>
            <group
              name="Torus003_13"
              position={[-1.944, 1.456, -2.197]}
              rotation={[-0.721, 0.387, 0.321]}
              scale={0.536}
            >
              <mesh
                name="Object_46"
                geometry={nodes.Object_46.geometry}
                material={materials.PaletteMaterial001}
                position={[0.378, -0.534, -0.43]}
                scale={1.082}
              />
              <mesh
                name="Object_47"
                geometry={nodes.Object_47.geometry}
                material={materials.PaletteMaterial004}
                position={[0.61, -1.039, -0.648]}
                scale={0.975}
              />
            </group>
            <group
              name="Torus004_14"
              position={[2.071, 1.434, -2.168]}
              rotation={[-0.721, 0.387, 0.321]}
              scale={0.536}
            >
              <mesh
                name="Object_49"
                geometry={nodes.Object_49.geometry}
                material={materials.PaletteMaterial001}
                position={[0.355, -0.518, -0.476]}
                scale={1.082}
              />
              <mesh
                name="Object_50"
                geometry={nodes.Object_50.geometry}
                material={materials.PaletteMaterial004}
                position={[0.587, -1.023, -0.694]}
                scale={0.975}
              />
            </group>
          </group>
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials.PaletteMaterial001}
            position={[0.153, 2.458, 0]}
            scale={4.364}
          />
          <mesh
            name="Object_5"
            geometry={nodes.Object_5.geometry}
            material={materials.PaletteMaterial002}
            position={[1.286, 1.993, 0]}
            scale={1.733}
          />
          <mesh
            name="Object_6"
            geometry={nodes.Object_6.geometry}
            material={materials.PaletteMaterial003}
            position={[-2.714, 1.668, 0]}
            scale={0.783}
          />
          <mesh
            name="Object_8"
            geometry={nodes.Object_8.geometry}
            material={materials.PaletteMaterial004}
            position={[2.062, 2.472, 0]}
            scale={4.043}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/car.glb');

export default Car;
