/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 castle.gltf 
Author: LZ Creation (https://sketchfab.com/jmch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fenis-castle-7c4e3bf96e7641b9987dde856547c3c3
Title: Fénis Castle
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Castle = (props) => {
  const { nodes, materials } = useGLTF('/castle.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.Fenis_Material_u1_v1}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/castle.gltf');

export default Castle;
