/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 castle.glb 
Author: LZ Creation (https://sketchfab.com/jmch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fenis-castle-7c4e3bf96e7641b9987dde856547c3c3
Title: Fénis Castle
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Castle = (props) => {
  const { nodes, materials } = useGLTF('/castle.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Fenis_Material_u1_v1}
          position={[3.439, 12.097, -1.764]}
          rotation={[-Math.PI, 0, 0]}
          scale={35.479}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/castle.glb');

export default Castle;
