/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 city.gltf 
Author: onerockett (https://sketchfab.com/onerockett)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-city-0ff5aed81b634278a161af8945140a6c
Title: Sci-fi City
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const City = (props) => {
  const { nodes, materials } = useGLTF('/city.gltf')
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group scale={0.01}>
          <group
            position={[-24.752, 1.454, 63.642]}
            rotation={[0, -0.661, 0]}
            scale={[0.488, 0.186, 0.214]}
          >
            <mesh
              geometry={nodes.Car1_White_cyan_0.geometry}
              material={materials.White_cyan}
            />
            <mesh
              geometry={nodes.Car1_Floor_0.geometry}
              material={materials.Floor}
            />
          </group>
          <mesh
            geometry={nodes.polySurface95_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window132_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-140.715, -29.511, 3.289]}
            rotation={[0, -0.73, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window137_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-188.54, 119.537, -30.43]}
            rotation={[0, 0.023, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window138_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-117.356, 65.221, 140.117]}
            rotation={[0, -0.78, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window139_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-69.587, 0.223, 159.759]}
            rotation={[0, 0.939, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window140_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-126.044, 38.092, 186.799]}
            rotation={[-Math.PI, -0.901, -Math.PI]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window141_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-150.578, -13.862, 155.293]}
            rotation={[0, -0.798, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window142_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-107.502, 73.532, 149.601]}
            rotation={[-Math.PI, 0.786, -Math.PI]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window143_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-136.079, 40.517, 176.114]}
            rotation={[0, 0.806, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window144_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-144.096, 16.107, 167.592]}
            rotation={[0, -0.801, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window145_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-126.845, -4.186, 131.945]}
            rotation={[0, -0.523, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window146_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-110.33, 64.906, 115.587]}
            rotation={[0, -0.679, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window148_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-131.024, 54.206, 205.653]}
            rotation={[-Math.PI, -1.422, -Math.PI]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window149_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-150.798, 85.461, 108.175]}
            rotation={[0, 0.758, 0]}
            scale={[8.161, 212.434, 7.304]}
          />
          <mesh
            geometry={nodes.Window152_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-123.926, 50.434, -3.955]}
            rotation={[0, -0.674, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window153_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-113.802, 48.869, 58.487]}
            rotation={[0, -0.526, 0]}
            scale={[15.31, 161.747, 15.31]}
          />
          <mesh
            geometry={nodes.Window154_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-164.2, 42.258, 87.624]}
            rotation={[0, -0.526, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window155_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-158.005, -31.18, 96.857]}
            rotation={[-Math.PI, -0.692, -Math.PI]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window156_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-131.991, 67.724, 72.318]}
            rotation={[0, -0.689, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window158_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-137.499, 54.136, 65.622]}
            rotation={[0, -0.652, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window159_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-154.86, 56.291, 33.958]}
            rotation={[0, -0.729, 0]}
            scale={[5.858, 161.347, 5.858]}
          />
          <mesh
            geometry={nodes.Window160_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-87.009, 54.494, 30.195]}
            rotation={[0, -0.672, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window161_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-142.844, 43.934, -24.151]}
            rotation={[-Math.PI, -0.876, -Math.PI]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window162_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-168.734, 54.469, -42.359]}
            rotation={[0, -0.007, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window163_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-155.469, 32.298, 51.384]}
            rotation={[0, -0.708, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window164_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-169.278, 55.575, -17.767]}
            rotation={[0, 0.004, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window165_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-116.32, 38.656, 5.048]}
            rotation={[0, -0.526, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window166_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-145.461, 47.093, 23.655]}
            rotation={[0, -0.676, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window167_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-96.439, 45.111, 60.135]}
            rotation={[-Math.PI, 0.661, -Math.PI]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window168_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-131.886, 54.875, 72.213]}
            rotation={[0, -0.719, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window169_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-169.589, 42.8, -2.155]}
            rotation={[0, 0.003, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window170_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-89.46, 34.256, 50.957]}
            rotation={[-Math.PI, -0.937, -Math.PI]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window171_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-161.179, 43.056, 44.424]}
            rotation={[0, 0.245, 0]}
            scale={[5.128, 161.347, 5.128]}
          />
          <mesh
            geometry={nodes.Window172_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-105.848, 47.233, 44.222]}
            rotation={[0, -0.713, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window173_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-148.821, 47.693, 27.331]}
            rotation={[0, -0.657, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window174_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-168.665, 36.19, 79.472]}
            rotation={[0, -1.074, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window175_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-126.621, 40.662, 42.179]}
            rotation={[-Math.PI, -0.895, -Math.PI]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Window176_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-92.088, 49.228, 22.309]}
            rotation={[0, -0.678, 0]}
            scale={[7.546, 161.347, 7.546]}
          />
          <mesh
            geometry={nodes.Forma_calle_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-112.039, -37.689, -13.197]}
            scale={[2.355, 0.265, 1]}
          />
          <mesh
            geometry={nodes.sweep1_Building_base_periferia_0.geometry}
            material={materials.Building_base_periferia}
          />
          <mesh
            geometry={nodes.sweep1_White_cyan_0.geometry}
            material={materials.White_cyan}
          />
          <mesh
            geometry={nodes.sweep2_Building_base_periferia_0.geometry}
            material={materials.Building_base_periferia}
          />
          <mesh
            geometry={nodes.sweep2_White_cyan_0.geometry}
            material={materials.White_cyan}
          />
          <mesh
            geometry={nodes.sweep3_Building_base_periferia_0.geometry}
            material={materials.Building_base_periferia}
          />
          <mesh
            geometry={nodes.sweep3_White_cyan_0.geometry}
            material={materials.White_cyan}
          />
          <mesh
            geometry={nodes.sweep4_Building_base_periferia_0.geometry}
            material={materials.Building_base_periferia}
          />
          <mesh
            geometry={nodes.sweep4_White_cyan_0.geometry}
            material={materials.White_cyan}
          />
          <mesh
            geometry={nodes.sweep5_Building_base_periferia_0.geometry}
            material={materials.Building_base_periferia}
          />
          <mesh
            geometry={nodes.sweep5_White_cyan_0.geometry}
            material={materials.White_cyan}
          />
          <group position={[-99.557, 0, 36.047]} scale={1031.474}>
            <mesh
              geometry={nodes.BL52_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.Window133_Amarillo_1_0.geometry}
              material={materials.Amarillo_1}
              position={[0.065, 0.111, 0.133]}
              rotation={[0, -0.727, 0]}
              scale={[0.016, 0.27, 0.014]}
            />
          </group>
          <group
            position={[-141.092, 79.86, -86.096]}
            rotation={[0, -0.384, 0]}
            scale={[3.605, 4.395, 3.605]}
          >
            <mesh
              geometry={nodes.BL14_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL14_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window98_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-130.573, 127.579, -120.924]}
            rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
            scale={5.599}
          >
            <mesh
              geometry={nodes.BL8_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL8_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL8_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.BL8_Cyan_0.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.Window92_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.Window121_Amarillo_0.geometry}
              material={materials.Amarillo}
              position={[0, -13.154, 0]}
            />
          </group>
          <group
            position={[-105.863, 120.832, -101.471]}
            rotation={[-Math.PI, -1.057, -Math.PI]}
            scale={4.028}
          >
            <mesh
              geometry={nodes.BL9_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL9_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.BL9_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL9_Cyan_0.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.Window93_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.Window120_Amarillo_0.geometry}
              material={materials.Amarillo}
              position={[0, -15.791, 0]}
            />
          </group>
          <group
            position={[-126.885, 104.479, -87.87]}
            rotation={[0, -0.432, 0]}
            scale={4.028}
          >
            <mesh
              geometry={nodes.BL9_Building_base_0_1.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL9_Amarillo_0_1.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.BL9_Pink_0_1.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL9_Cyan_0_1.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.Window93_Amarillo_0_1.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.Window120_Amarillo_0_1.geometry}
              material={materials.Amarillo}
              position={[0, -15.791, 0]}
            />
          </group>
          <group
            position={[-59.331, 42.72, 167.696]}
            rotation={[0, 0.921, 0]}
            scale={5.293}
          >
            <mesh
              geometry={nodes.BL8_Building_base_0_1.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL8_Pink_0_1.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window92_Amarillo_0_1.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-29.425, 59.066, 86.405]}
            rotation={[-Math.PI, -0.886, -Math.PI]}
            scale={5.293}
          >
            <mesh
              geometry={nodes.BL8_Building_base_0_2.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL8_Cyan_0_1.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.BL8_Amarillo_0_1.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.Window92_Amarillo_0_2.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-70.252, 35.196, 126.958]}
            rotation={[0, -0.65, 0]}
            scale={[7.951, 6.648, 7.951]}
          >
            <mesh
              geometry={nodes.BL33_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL33_Cyan_0.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.Window113_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-123.792, 44.736, -50.082]}
            rotation={[-Math.PI, -1.238, -Math.PI]}
            scale={[7.951, 6.648, 7.951]}
          >
            <mesh
              geometry={nodes.BL32_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL32_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window113_Amarillo_0_1.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-48.914, 60.093, 175.693]}
            rotation={[0, -0.487, 0]}
            scale={[7.951, 6.648, 7.951]}
          >
            <mesh
              geometry={nodes.BL31_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL31_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window113_Amarillo_0_2.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-85.532, 78.839, 116.056]}
            rotation={[0, -0.672, 0]}
            scale={[9.778, 29.961, 9.778]}
          >
            <mesh
              geometry={nodes.BL24_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL24_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL24_Cyan_0.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.Window98_Amarillo_0_1.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-170.016, 77.687, -134.179]}
            rotation={[0, -0.683, 0]}
            scale={4.753}
          >
            <mesh
              geometry={nodes.B23_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.B23_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window92_Amarillo_0_3.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-87.163, 48.932, 86.542]}
            rotation={[0, -0.645, 0]}
            scale={[7.087, 9.922, 7.087]}
          >
            <mesh
              geometry={nodes.BL14_Building_base_0_1.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL14_Pink_0_1.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL14_Cyan_0.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.Window98_Amarillo_0_2.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-102.86, 75.053, 101.551]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={5.764}
          >
            <mesh
              geometry={nodes.BL8_Building_base_0_3.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL8_Amarillo_0_2.geometry}
              material={materials.Amarillo}
            />
            <mesh
              geometry={nodes.BL8_Cyan_0_2.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.BL8_Pink_0_2.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window92_Amarillo_0_4.geometry}
              material={materials.Amarillo}
            />
          </group>
          <group
            position={[-13.466, 75.053, 110.944]}
            rotation={[0, Math.PI / 3, 0]}
            scale={5.764}
          >
            <mesh
              geometry={nodes.BL8_Building_base_0_4.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL8_Pink_0_3.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.Window92_Amarillo_0_5.geometry}
              material={materials.Amarillo}
            />
          </group>
          <mesh
            geometry={nodes.BL56_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window117_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-178.915, 22.013, 143.743]}
            rotation={[-Math.PI, 1.464, -Math.PI]}
            scale={[22.902, 16.46, 22.902]}
          />
          <mesh
            geometry={nodes.BL55_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL55_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL55_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window136_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-82.577, -8.969, 142.58]}
            rotation={[0, -0.644, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL53_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window135_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-74.171, 30.783, 77.294]}
            rotation={[0, -0.644, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL53_Building_base_0_1.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window134_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-34.08, 46.882, 77.02]}
            rotation={[0, -0.689, 0]}
            scale={[18.701, 278.029, 16.737]}
          />
          <mesh
            geometry={nodes.BL51_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window130_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-26.539, 47.3, 130.941]}
            rotation={[0, Math.PI / 3, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL50_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window126_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[8.385, 40.821, 25.225]}
            rotation={[0, 0.357, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL49_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL49_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window129_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-45.583, -14.006, 69.808]}
            rotation={[0, -0.644, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL48_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window127_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-38.048, 61.372, 128.06]}
            rotation={[0, -0.644, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL46_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL46_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL46_REd_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.Window125_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-41.263, 63.17, 96.892]}
            rotation={[0, -0.644, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL45_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window124_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[18.559, 91.908, 20.859]}
            rotation={[0, 0.401, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL21_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL21_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window105_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-176.164, 90.321, -108.364]}
            rotation={[-Math.PI, -1.219, -Math.PI]}
            scale={23.343}
          />
          <mesh
            geometry={nodes.BL43_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL43_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window123_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-116.2, 90.217, -49.203]}
            rotation={[0, 1.121, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL42_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL42_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window122_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-146.199, 90.722, -128.105]}
            rotation={[-Math.PI, -1.082, -Math.PI]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL37_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window118_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-151.52, 50.293, -101.062]}
            rotation={[0, -0.523, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.Window119_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-151.52, 50.342, -101.062]}
            rotation={[0, -0.523, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL35_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window115_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
            position={[-172.22, 54.15, 172.425]}
            rotation={[0, -1.464, 0]}
            scale={[22.902, 14.128, 22.902]}
          />
          <mesh
            geometry={nodes.BL34_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL34_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window114_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[15.617, 88.407, 37.098]}
            rotation={[0, 0.383, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL30_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL30_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.Window113_Amarillo_0_3.geometry}
            material={materials.Amarillo}
            position={[-93.867, 48.882, -108.804]}
            rotation={[0, -0.523, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL29_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL29_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL29_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.Window104_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-27.944, 92.83, 119.366]}
            rotation={[-Math.PI, 0.538, -Math.PI]}
            scale={23.343}
          />
          <group position={[-99.557, 0, 36.047]} scale={1031.474}>
            <mesh
              geometry={nodes.BL28_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL28_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
          </group>
          <mesh
            geometry={nodes.Window110_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-17.996, 85.326, 152.436]}
            rotation={[0, 0.927, 0]}
            scale={23.343}
          />
          <mesh
            geometry={nodes.BL27_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL27_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window109_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-97.902, -28.659, 129.697]}
            rotation={[0, -0.522, 0]}
            scale={23.343}
          />
          <mesh
            geometry={nodes.BL26_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window108_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-10.801, 95.339, 93.381]}
            rotation={[0, -0.522, 0]}
            scale={23.343}
          />
          <mesh
            geometry={nodes.BL25_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window147_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-147.666, 92.82, -74.527]}
            rotation={[0, -0.644, 0]}
            scale={22.902}
          />
          <mesh
            geometry={nodes.BL22_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL22_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL22_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window106_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-57.01, 88.924, 110.981]}
            rotation={[0, -0.522, 0]}
            scale={23.343}
          />
          <mesh
            geometry={nodes.BL21_Building_base_0_1.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL21_Amarillo_0_1.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window105_Amarillo_0_1.geometry}
            material={materials.Amarillo}
            position={[-176.164, 90.321, -108.364]}
            rotation={[-Math.PI, -1.219, -Math.PI]}
            scale={23.343}
          />
          <mesh
            geometry={nodes.BL20_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL20_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window89_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-45.809, 46.99, 145.508]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL19_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window100_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-63.721, 59.883, 82.067]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.Window101_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-61.415, 43.07, 85.566]}
            rotation={[-Math.PI, 0.533, -Math.PI]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL17_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL17_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window99_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-74.545, 60.033, 96.32]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <group position={[9.132, 0, 22.063]} scale={[1.372, 1, 1.372]}>
            <mesh
              geometry={nodes.BL14_Building_base_0_2.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL14_Pink_0_2.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL14_Cyan_0_1.geometry}
              material={materials.Cyan}
            />
          </group>
          <mesh
            geometry={nodes.Window98_Amarillo_0_3.geometry}
            material={materials.Amarillo}
            position={[-36.586, 61.088, -51.145]}
            rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL13_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL13_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window97_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-81.931, 56.875, -7.336]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL12_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL12_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window96_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-59.235, 56.884, 56.799]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL11_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL11_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL11_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window95_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-62.539, 14.986, 51.223]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL10_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.Window94_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-65.698, 57.959, 70.435]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL9_Building_base_0_2.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL9_Pink_0_2.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL9_Cyan_0_2.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window93_Amarillo_0_2.geometry}
            material={materials.Amarillo}
            position={[-103.189, -11.284, -25.03]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL8_Building_base_0_5.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL8_Pink_0_4.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.Window92_Amarillo_0_6.geometry}
            material={materials.Amarillo}
            position={[-58.451, -1.562, 0.217]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL7_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL7_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL7_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL7_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window91_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-14.841, 62.77, 40.308]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL6_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL6_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL6_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.Window90_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-133.62, 3.751, -61.186]}
            rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL5_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL5_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.Window88_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-111.379, 64.307, -76.26]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <group
            position={[-67.4, 161.696, -66.296]}
            rotation={[0, -0.497, 0]}
            scale={18.324}
          >
            <mesh
              geometry={nodes.BL4_Building_base_0.geometry}
              material={materials.Building_base}
            />
            <mesh
              geometry={nodes.BL4_Pink_0.geometry}
              material={materials.Pink}
            />
            <mesh
              geometry={nodes.BL4_Cyan_0.geometry}
              material={materials.Cyan}
            />
            <mesh
              geometry={nodes.BL4_REd_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.BL4_Amarillo_0.geometry}
              material={materials.Amarillo}
            />
          </group>
          <mesh
            geometry={nodes.Window87_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-66.977, 226.552, -66.441]}
            rotation={[0, Math.PI / 3, 0]}
            scale={21.954}
          />
          <mesh
            geometry={nodes.BL3_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL3_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL3_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL3_REd_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.BL3_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window63_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[6.845, 0, 4.426]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window79_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-115.866, 0.245, -137.567]}
          />
          <mesh
            geometry={nodes.Window80_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-130.879, 0.245, 130.715]}
            rotation={[-Math.PI, 1.52, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window64_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[6.845, 0, 4.426]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window65_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[6.845, 0, 4.426]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window66_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[6.845, 0, 4.426]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window67_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[6.845, 67.376, 4.426]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window68_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[6.845, 62.965, 4.426]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window69_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[24.062, 62.965, -40.035]}
            rotation={[0, 0.043, 0]}
          />
          <mesh
            geometry={nodes.Window70_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[24.062, 16.824, -40.035]}
            rotation={[0, 0.043, 0]}
          />
          <mesh
            geometry={nodes.Window71_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-31.762, 62.965, -10.112]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window72_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-31.762, 2.407, -10.112]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window73_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[15.992, 67.376, -4.013]}
            rotation={[-Math.PI, -1.549, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window74_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[35.84, 200.837, -36.685]}
            rotation={[Math.PI, -0.501, 0]}
          />
          <mesh
            geometry={nodes.Window75_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[35.84, 157.017, -36.685]}
            rotation={[Math.PI, -0.501, 0]}
          />
          <mesh
            geometry={nodes.Window76_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[35.84, 96.02, -36.685]}
            rotation={[Math.PI, -0.501, 0]}
          />
          <mesh
            geometry={nodes.Window77_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[15.992, 6.379, -4.013]}
            rotation={[-Math.PI, -1.549, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window78_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[35.84, 139.84, -36.685]}
            rotation={[Math.PI, -0.501, 0]}
          />
          <mesh
            geometry={nodes.Window81_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[26.015, 61.075, -39.039]}
            rotation={[0, 0.043, 0]}
          />
          <mesh
            geometry={nodes.Window82_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[10.683, 50.752, 6.506]}
            rotation={[0, -1.553, 0]}
          />
          <mesh
            geometry={nodes.Window83_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-33.382, 65.188, -7.121]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window84_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-16.72, 50.752, -51.354]}
            rotation={[-Math.PI, 1.56, -Math.PI]}
          />
          <mesh
            geometry={nodes.BL2_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL2_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL2_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL2_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window41_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-94.55, -13.438, -68.39]}
            rotation={[-Math.PI, 1.522, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window42_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-94.55, -13.438, -68.39]}
            rotation={[-Math.PI, 1.522, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window43_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-94.55, -13.438, -68.39]}
            rotation={[-Math.PI, 1.522, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window44_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-94.55, -13.438, -68.39]}
            rotation={[-Math.PI, 1.522, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window45_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-94.55, -80.658, -68.39]}
            rotation={[-Math.PI, 1.522, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window54_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-49.525, 31.596, -51.681]}
            rotation={[0, 0.044, 0]}
          />
          <mesh
            geometry={nodes.Window55_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-59.419, 8.986, -8.554]}
            rotation={[0, -1.53, 0]}
          />
          <mesh
            geometry={nodes.Window56_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-59.419, -80.658, -8.554]}
            rotation={[0, -1.53, 0]}
          />
          <mesh
            geometry={nodes.Window57_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-59.419, -30.317, -8.554]}
            rotation={[0, -1.53, 0]}
          />
          <mesh
            geometry={nodes.Window58_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-103.436, 31.596, -24.535]}
            rotation={[-Math.PI, -0.067, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window59_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-103.542, -13.438, -24.526]}
            rotation={[-Math.PI, -0.067, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window60_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-103.542, -31.005, -24.526]}
            rotation={[-Math.PI, -0.067, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window61_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-103.542, -70.98, -24.526]}
            rotation={[-Math.PI, -0.067, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window62_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-59.433, -13.438, -8.541]}
            rotation={[0, -1.528, 0]}
          />
          <mesh
            geometry={nodes.BL1_Building_base_0.geometry}
            material={materials.Building_base}
          />
          <mesh
            geometry={nodes.BL1_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.BL1_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.BL1_REd_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.BL1_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window19_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[0.035, 0, -0.064]}
          />
          <mesh
            geometry={nodes.Window38_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[0.035, 0, -0.064]}
          />
          <mesh
            geometry={nodes.Window10_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[0.035, 0, -0.064]}
          />
          <mesh
            geometry={nodes.Window20_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[0.035, 0, -0.064]}
          />
          <mesh
            geometry={nodes.Window40_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.Window46_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-40.75, 10.219, -21.126]}
            rotation={[-Math.PI, 1.561, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window47_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-40.75, 8.212, -21.126]}
            rotation={[-Math.PI, 1.561, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window48_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-40.75, 0, -21.126]}
            rotation={[-Math.PI, 1.561, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window49_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-40.75, -56.614, -21.126]}
            rotation={[-Math.PI, 1.561, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window50_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-52.661, 27.68, 17.512]}
            rotation={[-Math.PI, -0.003, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window51_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-53.406, 27.68, 18.932]}
            rotation={[-Math.PI, -0.005, -Math.PI]}
          />
          <mesh
            geometry={nodes.Window52_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-8.586, 12.726, 39.092]}
            rotation={[0, -1.559, 0]}
          />
          <mesh
            geometry={nodes.Window53_Amarillo_0.geometry}
            material={materials.Amarillo}
            position={[-43.166, 71.093, -22.838]}
            rotation={[-Math.PI, 1.566, -Math.PI]}
          />
          <group
            position={[-25.372, 0.458, -33.704]}
            rotation={[-Math.PI, 0.48, -Math.PI]}
            scale={[3.537, 1, 24.347]}
          >
            <mesh
              geometry={nodes.Tunel7_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel7_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-157.925, 0.458, -131.223]}
            rotation={[-Math.PI, 0.48, -Math.PI]}
            scale={[3.537, 1, 24.347]}
          >
            <mesh
              geometry={nodes.Tunel6_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel6_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-181.454, 0.458, -116.997]}
            rotation={[-Math.PI, 0.28, -Math.PI]}
            scale={[3.537, 1, 24.347]}
          >
            <mesh
              geometry={nodes.Tunel5_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel5_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[26.924, -6.218, -192.888]}
            rotation={[-Math.PI, 0.277, Math.PI]}
            scale={[-1, 1, 1]}
          >
            <mesh
              geometry={nodes.Tunel4_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel4_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-156.418, 0.458, 142.433]}
            rotation={[0, -0.861, 0]}
            scale={[3.537, 1, 24.347]}
          >
            <mesh
              geometry={nodes.Tunel3_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel3_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-158.973, 0.458, 139.459]}
            rotation={[0, -0.861, 0]}
            scale={[3.537, 1, 24.347]}
          >
            <mesh
              geometry={nodes.Tunel2_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel2_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-161.45, 0.458, 136.575]}
            rotation={[0, -0.861, 0]}
            scale={[3.537, 1, 24.347]}
          >
            <mesh
              geometry={nodes.Tunel1_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel1_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[-104.583, 0.458, 178.816]}
            rotation={[0, -0.861, 0]}
            scale={[3.537, 1, 29.239]}
          >
            <mesh
              geometry={nodes.Tunel_Tunels1_0.geometry}
              material={materials.Tunels1}
            />
            <mesh
              geometry={nodes.Tunel_REd_0.geometry}
              material={materials.material}
            />
          </group>
          <mesh
            geometry={nodes.polySurface97_Building_base_periferia_0.geometry}
            material={materials.Building_base_periferia}
          />
          <mesh
            geometry={nodes.polySurface97_Floor_0.geometry}
            material={materials.Floor}
          />
          <mesh
            geometry={nodes.polySurface97_White_cyan_0.geometry}
            material={materials.White_cyan}
          />
          <mesh
            geometry={nodes.polySurface97_Tunels1_0.geometry}
            material={materials.Tunels1}
          />
          <mesh
            geometry={nodes.polySurface97_Cyan_0.geometry}
            material={materials.Cyan}
          />
          <mesh
            geometry={nodes.polySurface97_Pink_0.geometry}
            material={materials.Pink}
          />
          <mesh
            geometry={nodes.polySurface97_Amarillo_0.geometry}
            material={materials.Amarillo}
          />
          <mesh
            geometry={nodes.polySurface97_REd_0.geometry}
            material={materials.material}
          />
          <mesh
            geometry={nodes.polySurface97_Amarillo_1_0.geometry}
            material={materials.Amarillo_1}
          />
          <mesh
            geometry={nodes.polySurface97_Black_0.geometry}
            material={materials.Black}
          />
        </group>
      </lOD>
    </group>
  );
}

useGLTF.preload('/city.gltf')

export default City