/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 city.glb 
Author: onerockett (https://sketchfab.com/onerockett)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-city-0ff5aed81b634278a161af8945140a6c
Title: Sci-fi City
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const City = (props) => {
  const { nodes, materials } = useGLTF('/city.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.polySurface95_Building_base_0.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.817, 0.789, 0.293]}
          scale={1.786}
        />
        <mesh
          geometry={nodes.Window132_Amarillo_1_0.geometry}
          material={materials.PaletteMaterial002}
          position={[-1.239, -0.033, 0.052]}
          rotation={[0, -0.73, 0]}
          scale={[1.053, 27.398, 0.942]}
        />
        <mesh
          geometry={nodes.Forma_calle_lambert1_0.geometry}
          material={materials.PaletteMaterial003}
          position={[-0.831, 0.633, 0.222]}
          scale={[9.008, 1.014, 3.825]}
        />
        <mesh
          geometry={nodes.BL55_Pink_0.geometry}
          material={materials.PaletteMaterial004}
          position={[-0.815, 0.736, 0.179]}
          scale={1.66}
        />
        <mesh
          geometry={nodes.BL55_Cyan_0.geometry}
          material={materials.PaletteMaterial005}
          position={[-0.724, 0.799, 0.01]}
          scale={1.416}
        />
        <instancedMesh
          args={[
            nodes.Tunel5_Tunels1_0.geometry,
            materials.PaletteMaterial003,
            5,
          ]}
          instanceMatrix={nodes.Tunel5_Tunels1_0.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Tunel5_REd_0.geometry, materials.PaletteMaterial005, 5]}
          instanceMatrix={nodes.Tunel5_REd_0.instanceMatrix}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/city.glb');

export default City;
