/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 compass.glb 
Author: Balen96 (https://sketchfab.com/Balen96)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/compass-c7448070b8c544608976f47b43a063ec
Title: Compass
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

const Compass = (props) => {
  const { nodes, materials } = useGLTF('/compass.glb');
  const ref = useRef();

  useFloating(ref);
  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Cover_low_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0.041, 0.062, 0]}
          rotation={[0, 0, 2.094]}
          scale={0.089}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/compass.glb');

export default Compass;
