/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dinosaur.gltf 
Author: MrTomas (https://sketchfab.com/MrTomas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dinosaur-38e1ae4d19cb417eb78a034ee7786e06
Title: Dinosaur
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

const Dinosaur = (props) => {
  const { nodes, materials } = useGLTF('/dinosaur.gltf');
  const ref = useRef();

  useFloating(ref);

  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <group
          position={[-0.785, 0, -4.596]}
          rotation={[-Math.PI / 2, 0, -0.128]}
        >
          <group position={[34.418, 0, -19.949]}>
            <mesh
              geometry={nodes['Deinonych__Material_#36_0'].geometry}
              material={materials.Material_36}
            />
            <mesh
              geometry={nodes['Deinonych__Material_#36_0_1'].geometry}
              material={materials.Material_36_0}
            />
            <mesh
              geometry={nodes['Deinonych__Material_#36_0_2'].geometry}
              material={materials.Material_36_1}
            />
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/dinosaur.gltf');

export default Dinosaur;
