/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dinosaur.glb 
Author: MrTomas (https://sketchfab.com/MrTomas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dinosaur-38e1ae4d19cb417eb78a034ee7786e06
Title: Dinosaur
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

const Dinosaur = (props) => {
  const { nodes, materials } = useGLTF('/dinosaur.glb');
  const ref = useRef();

  props.floating && useFloating(ref);

  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes['Deinonych__Material_#36_0'].geometry}
          material={materials.Material_36}
          position={[35.429, 0.848, -8.42]}
          rotation={[-Math.PI / 2, 0, -0.128]}
          scale={55.677}
        />
        <mesh
          geometry={nodes['Deinonych__Material_#36_0_1'].geometry}
          material={materials.Material_36_0}
          position={[40.384, -1.37, -46.708]}
          rotation={[-Math.PI / 2, 0, -0.128]}
          scale={28.548}
        />
        <mesh
          geometry={nodes['Deinonych__Material_#36_0_2'].geometry}
          material={materials.Material_36_1}
          position={[41.551, 29.459, -55.841]}
          rotation={[-Math.PI / 2, 0, -0.128]}
          scale={2.424}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/dinosaur.glb');
export default Dinosaur;
