/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dragon.gltf 
Author: Nonexistent 101 (https://sketchfab.com/Nonexistent101)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/european-dragon-82f393a2e6c048ad80c171ce3b3a7b87
Title: European Dragon
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Dragon = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/dragon.gltf');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.134}
          >
            <group
              name="SKM_Dragon_animationsfbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group
                    name="Dragon"
                    position={[0, 396.324, 0]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  />
                  <group
                    name="Root"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  >
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <group
                        name="Object_8"
                        position={[0, 396.324, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      />
                      <group
                        name="Object_178"
                        position={[0, 696.4, 229.827]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      />
                      <group
                        name="Object_180"
                        position={[0, 696.4, 229.827]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      />
                      <group
                        name="Object_182"
                        position={[0, 0, 113.399]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      />
                      <group
                        name="Object_184"
                        position={[0, 0, 113.399]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                      />
                      <skinnedMesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.Low_Poly_Bake}
                        skeleton={nodes.Object_9.skeleton}
                      />
                      <skinnedMesh
                        name="Object_179"
                        geometry={nodes.Object_179.geometry}
                        material={materials['Material.002']}
                        skeleton={nodes.Object_179.skeleton}
                      />
                      <skinnedMesh
                        name="Object_181"
                        geometry={nodes.Object_181.geometry}
                        material={materials['Material.003']}
                        skeleton={nodes.Object_181.skeleton}
                      />
                      <skinnedMesh
                        name="Object_183"
                        geometry={nodes.Object_183.geometry}
                        material={materials['Material.001']}
                        skeleton={nodes.Object_183.skeleton}
                      />
                      <skinnedMesh
                        name="Object_185"
                        geometry={nodes.Object_185.geometry}
                        material={materials['Material.001']}
                        skeleton={nodes.Object_185.skeleton}
                      />
                    </group>
                  </group>
                  <group
                    name="Teeth_Bottom"
                    position={[0, 696.4, 229.827]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  />
                  <group
                    name="Teeth_Top"
                    position={[0, 696.4, 229.827]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  />
                  <group
                    name="Eye_Right"
                    position={[0, 0, 113.399]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  />
                  <group
                    name="Eye_Left"
                    position={[0, 0, 113.399]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/dragon.gltf');

export default Dragon;
