/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 environment.gltf 
Author: Ignacio (https://sketchfab.com/tasius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/victorian-era-inspired-modular-environment-e5d9e1315a4643f5bee7a019d2086b99
Title: Victorian era-inspired modular environment
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Environment = (props) => {
  const { nodes, materials } = useGLTF('/environment.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[1123.29, 305.136, -0.417]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <group position={[-252.915, 174.487, -651.616]}>
                <mesh
                  geometry={nodes.ARCO_BUENO007_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.ARCO_BUENO007_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.ARCO_BUENO007_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[525.804, 0, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-1197.086, -1181.081, 0]}>
                <mesh
                  geometry={nodes.TECHO_PROFE004_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.TECHO_PROFE004_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.TECHO_PROFE004_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[1192.26, 609.864, -0.417]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.TECHO_PROFE006_RED_BRICKS_0.geometry}
                material={materials.RED_BRICKS}
                position={[-1197.086, -400.277, -611.015]}
              />
            </group>
            <group
              position={[1772.26, 0, 824.583]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3621.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_039_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_039_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
            <group
              position={[1446.862, 609.864, 254.583]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE019_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.484, -985.279, -610.999]}
              />
            </group>
            <group
              position={[-1.779, 0, 525.805]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-325, -1.02, 0]}>
                <mesh
                  geometry={nodes.Plane001_SUELO_0.geometry}
                  material={materials.SUELO}
                />
                <mesh
                  geometry={nodes.Plane001_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.Plane001_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
            <group
              position={[1123.29, 0.13, 549.583]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3346.412, -626.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_050_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_050_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.culumna_nueva_050_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[1123.29, 0, -0.417]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane002_SUELO_0.geometry}
                material={materials.SUELO}
                position={[50.826, 3094.925, 0]}
              />
            </group>
            <group
              position={[625.804, 0.13, -225]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3121.829, -726.414, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_051_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_051_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.culumna_nueva_051_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[1773.29, 0, -325.417]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane003_SUELO_0.geometry}
                material={materials.SUELO}
                position={[-599.174, 2769.925, 0]}
              />
            </group>
            <group
              position={[1123.29, 0, 649.583]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane004_SUELO_0.geometry}
                material={materials.SUELO}
                position={[50.826, 3094.925, 0]}
              />
            </group>
            <group
              position={[1772.26, 0.13, -225]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3121.829, -726.414, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_054_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_054_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
            <group
              position={[1448.808, 609.864, -255.416]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE020_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -1025.279, -611.015]}
              />
            </group>
            <group
              position={[1702.26, 604.624, 549.583]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.TECHO_PROFE007_RED_BRICKS_0.geometry}
                material={materials.RED_BRICKS}
                position={[-1197.086, -910.278, -611.015]}
              />
            </group>
            <group
              position={[1447.26, 609.88, 804.582]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE021_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.484, -985.279, -610.999]}
              />
            </group>
            <group
              position={[815.783, 305.136, 850.805]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <group position={[-252.915, 174.487, -651.616]}>
                <mesh
                  geometry={nodes.ARCO_BUENO008_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.ARCO_BUENO008_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.ARCO_BUENO008_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[814.752, 0.13, 850.805]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            >
              <group position={[-3346.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_055_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_055_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.culumna_nueva_055_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[0, 0.13, -525.804]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <group position={[-3346.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_056_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_056_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.culumna_nueva_056_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[1123.013, 0, -225]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3671.412, -626.415, 0.13]}>
                <mesh
                  geometry={nodes.culumna_nueva_057_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_057_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.culumna_nueva_057_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[1152.259, 609.864, -0.417]}
              rotation={[-Math.PI / 2, 0, -1.571]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE022_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -985.279, -611.015]}
              />
            </group>
            <group
              position={[1702.26, 604.624, -550.416]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.TECHO_PROFE008_RED_BRICKS_0.geometry}
                material={materials.RED_BRICKS}
                position={[-1197.086, -910.278, -611.015]}
              />
            </group>
            <group
              position={[1772.26, 0, -825]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3621.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_058_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_058_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
            <group
              position={[1448.013, 609.864, -845.417]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE023_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.484, -985.279, -610.999]}
              />
            </group>
            <group
              position={[1702.26, 609.864, -550.416]}
              rotation={[-Math.PI / 2, 0, -1.571]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE024_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -985.279, -611.015]}
              />
            </group>
            <group
              position={[1702.26, 609.864, 549.583]}
              rotation={[-Math.PI / 2, 0, -1.571]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE025_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -985.279, -611.015]}
              />
            </group>
            <group
              position={[-525.804, 0.13, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3346.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_059_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_059_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
                <mesh
                  geometry={nodes.culumna_nueva_059_SUELO_0.geometry}
                  material={materials.SUELO}
                />
              </group>
            </group>
            <group
              position={[1988.863, 609.864, 254.583]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE026_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.484, -985.279, -610.999]}
              />
            </group>
            <group
              position={[1990.809, 609.864, -255.416]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE027_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -1025.279, -611.015]}
              />
            </group>
            <group
              position={[1989.26, 609.88, 804.582]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE028_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.484, -985.279, -610.999]}
              />
            </group>
            <group
              position={[1990.014, 609.864, -845.417]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE029_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.484, -985.279, -610.999]}
              />
            </group>
            <group
              position={[2244.261, 609.864, -550.416]}
              rotation={[-Math.PI / 2, 0, -1.571]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE030_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -985.279, -611.015]}
              />
            </group>
            <group
              position={[2244.261, 609.864, 549.583]}
              rotation={[-Math.PI / 2, 0, -1.571]}
            >
              <mesh
                geometry={nodes.ARCO_PROFE031_PIEDRA_0.geometry}
                material={materials.PIEDRA}
                position={[-1197.086, -985.279, -611.015]}
              />
            </group>
            <group
              position={[1773.29, 0, -0.417]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane005_SUELO_0.geometry}
                material={materials.SUELO}
                position={[50.826, 3094.925, 0]}
              />
            </group>
            <group
              position={[1773.29, 0, -325.417]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane006_SUELO_0.geometry}
                material={materials.SUELO}
                position={[50.826, 2769.925, 0]}
              />
            </group>
            <group
              position={[1773.29, 0, 649.583]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.Plane007_SUELO_0.geometry}
                material={materials.SUELO}
                position={[50.826, 3094.925, 0]}
              />
            </group>
            <group
              position={[1734.261, 609.864, -0.417]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.TECHO_PROFE009_RED_BRICKS_0.geometry}
                material={materials.RED_BRICKS}
                position={[-1197.086, -400.277, -611.015]}
              />
            </group>
            <group
              position={[2244.261, 604.624, 549.583]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.TECHO_PROFE010_RED_BRICKS_0.geometry}
                material={materials.RED_BRICKS}
                position={[-1197.086, -910.278, -611.015]}
              />
            </group>
            <group
              position={[2244.261, 604.624, -550.416]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.TECHO_PROFE011_RED_BRICKS_0.geometry}
                material={materials.RED_BRICKS}
                position={[-1197.086, -910.278, -611.015]}
              />
            </group>
            <group
              position={[2314.261, 0, 824.583]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3621.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_060_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_060_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
            <group
              position={[2314.261, 0.13, -225]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3121.829, -726.414, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_061_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_061_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
            <group
              position={[2314.261, 0, -825]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <group position={[-3621.412, -726.415, 0]}>
                <mesh
                  geometry={nodes.culumna_nueva_062_PIEDRA_0.geometry}
                  material={materials.PIEDRA}
                />
                <mesh
                  geometry={nodes.culumna_nueva_062_RED_BRICKS_0.geometry}
                  material={materials.RED_BRICKS}
                />
              </group>
            </group>
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/environment.gltf');

export default Environment;
