/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 environment.glb 
Author: Ignacio (https://sketchfab.com/tasius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/victorian-era-inspired-modular-environment-e5d9e1315a4643f5bee7a019d2086b99
Title: Victorian era-inspired modular environment
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Environment = (props) => {
  const { nodes, materials } = useGLTF('/environment.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.ARCO_BUENO007_PIEDRA_0.geometry}
          material={materials.PIEDRA}
          position={[1.097, 0.378, 0.186]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.766}
        />
        <mesh
          geometry={nodes.ARCO_BUENO007_RED_BRICKS_0.geometry}
          material={materials.RED_BRICKS}
          position={[1.079, 0.416, 0.186]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.766}
        />
        <mesh
          geometry={nodes.ARCO_BUENO007_SUELO_0.geometry}
          material={materials.SUELO}
          position={[0.37, 0, 0.402]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.053}
        />
        <instancedMesh
          args={[nodes.ARCO_PROFE019_PIEDRA_0.geometry, materials.PIEDRA, 13]}
          instanceMatrix={nodes.ARCO_PROFE019_PIEDRA_0.instanceMatrix}
        />
        <instancedMesh
          args={[
            nodes.culumna_nueva_050_PIEDRA_0.geometry,
            materials.PIEDRA,
            5,
          ]}
          instanceMatrix={nodes.culumna_nueva_050_PIEDRA_0.instanceMatrix}
        />
        <instancedMesh
          args={[
            nodes.culumna_nueva_050_RED_BRICKS_0.geometry,
            materials.RED_BRICKS,
            5,
          ]}
          instanceMatrix={nodes.culumna_nueva_050_RED_BRICKS_0.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.culumna_nueva_050_SUELO_0.geometry, materials.SUELO, 6]}
          instanceMatrix={nodes.culumna_nueva_050_SUELO_0.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Plane002_SUELO_0.geometry, materials.SUELO, 6]}
          instanceMatrix={nodes.Plane002_SUELO_0.instanceMatrix}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/environment.glb');

export default Environment;
