/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fire.gltf 
Author: Scott VanArsdale (https://sketchfab.com/vanart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-fantasy-camp-fire-asset-611b74668b0b450c9668e2938fde54b3
Title: Medieval Fantasy - Camp Fire Asset
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Fire = (props) => {
  const { nodes, materials } = useGLTF('/fire.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.campFire_SHDR}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/fire.gltf');

export default Fire;
