/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ground.glb 
Author: Meerschaum Digital (https://sketchfab.com/meerschaumdigital)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stone-ground-texture-seamless-4k-pbr-2f9a941bc88b491091a6c54b566da4c1
Title: Stone Ground Texture (Seamless / 4K PBR)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Ground = (props) => {
  const { nodes, materials } = useGLTF('/ground.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Stone_Ground_Material001_0.geometry}
          material={materials['Material.001']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={745.581}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/ground.glb');

export default Ground;
