/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hallway.glb 
Author: (Allie) Oleksandra Almikieieva (https://sketchfab.com/allie222)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diorama-haunted-hallway-ab943bb1b1f54b39ba932d36b49f3fa3
Title: Diorama Haunted Hallway
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Hallway = (props) => {
  const { nodes, materials } = useGLTF('/hallway.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.floor_Wood_0.geometry}
          material={materials.Wood}
          position={[0, -0.078, 0]}
          scale={5}
        />
        <mesh
          geometry={nodes.wall_Wallpaper_0.geometry}
          material={materials.Wallpaper}
          position={[-0.084, 2.295, 0.004]}
          rotation={[0, 0, Math.PI / 2]}
          scale={5.005}
        />
        <mesh
          geometry={nodes.wall_TrimSheet_0.geometry}
          material={materials.TrimSheet}
          position={[-0.083, 1.66, 0.004]}
          rotation={[0, 0, Math.PI / 2]}
          scale={5.005}
        />
        <mesh
          geometry={nodes.carpet_Fabric_0.geometry}
          material={materials.Fabric}
          position={[-0.02, 0.01, 0]}
          scale={3.597}
        />
        <mesh
          geometry={nodes.Clock_clocksMATshader_0.geometry}
          material={materials.clocksMATshader}
          position={[-1.305, 1.033, 3.67]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.033}
        />
        <mesh
          geometry={nodes.Paint_PaintMAT_0.geometry}
          material={materials.PaintMAT}
          position={[-1.467, 2.095, -3.198]}
          scale={0.6}
        />
        <mesh
          geometry={nodes.table_TableMAT_0.geometry}
          material={materials.TableMAT}
          position={[-0.983, 0.474, 1.955]}
          scale={0.787}
        />
        <mesh
          geometry={nodes.Vase_VaseMAT_0.geometry}
          material={materials.VaseMAT}
          position={[-0.9, 1.362, 1.922]}
          rotation={[-0.003, -0.163, 0]}
          scale={0.411}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/hallway.glb');

export default Hallway;
