/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hallway.gltf 
Author: (Allie) Oleksandra Almikieieva (https://sketchfab.com/allie222)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diorama-haunted-hallway-ab943bb1b1f54b39ba932d36b49f3fa3
Title: Diorama Haunted Hallway
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Hallway = (props) => {
  const { nodes, materials } = useGLTF('/hallway.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group scale={0.01}>
          <group position={[-150, 175, 0.901]} rotation={[0, 0, Math.PI / 2]}>
            <mesh
              geometry={nodes.wall_Wallpaper_0.geometry}
              material={materials.Wallpaper}
            />
            <mesh
              geometry={nodes.wall_TrimSheet_0.geometry}
              material={materials.TrimSheet}
            />
          </group>
          <group position={[-148.245, 209.465, -319.819]}>
            <mesh
              geometry={nodes.Paint_TrimSheet_0.geometry}
              material={materials.TrimSheet}
            />
            <mesh
              geometry={nodes.Paint_PaintMAT_0.geometry}
              material={materials.PaintMAT}
            />
          </group>
          <mesh
            geometry={nodes.floor_Wood_0.geometry}
            material={materials.Wood}
          />
          <mesh
            geometry={nodes.door_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-141.945, 2.713, 0]}
          />
          <mesh
            geometry={nodes.door2_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-141.945, 127.713, 0]}
            scale={[1, 0.999, 1]}
          />
          <mesh
            geometry={nodes.arch_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[0, 0, 17]}
          />
          <mesh
            geometry={nodes.door_hand_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-136.003, 125.254, 50.026]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={1.987}
          />
          <mesh
            geometry={nodes.lamp_1_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-148, 209.228, 170.308]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1, 1, 0.639]}
          />
          <mesh
            geometry={nodes.lamp_2_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-145.101, 208.767, 170.374]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.lamp_3_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-136.183, 216.571, 170.374]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.lamp_top_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-136.168, 225.479, 170.347]}
          />
          <mesh
            geometry={nodes.carpet_Fabric_0.geometry}
            material={materials.Fabric}
            position={[-2.033, 0, 0]}
          />
          <mesh
            geometry={nodes.circle_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.945, 445.274]}
            rotation={[1.763, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.wall2_Wallpaper_0.geometry}
            material={materials.Wallpaper}
            position={[0, 0, 157.959]}
          />
          <mesh
            geometry={nodes.circle1_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.976, 335.848]}
            rotation={[1.772, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.circle2_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.945, 226.375]}
            rotation={[1.763, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.circle3_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.976, 116.939]}
            rotation={[1.772, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.circle4_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.945, -116.943]}
            rotation={[1.763, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.circle5_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.976, -226.44]}
            rotation={[1.772, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.circle6_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.945, -335.848]}
            rotation={[1.763, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.circle7_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-152.682, 51.976, -445.33]}
            rotation={[1.772, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.lamp_top1_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-136.168, 225.479, -167.148]}
          />
          <mesh
            geometry={nodes.lamp_4_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-136.183, 216.571, -167.121]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh
            geometry={nodes.lamp_5_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-145.101, 208.767, -167.121]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.lamp_6_TrimSheet_0.geometry}
            material={materials.TrimSheet}
            position={[-148, 209.228, -167.187]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1, 1, 0.639]}
          />
          <mesh
            geometry={nodes.Clock_clocksMATshader_0.geometry}
            material={materials.clocksMATshader}
            position={[-130.529, 0, 366.967]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.table_TableMAT_0.geometry}
            material={materials.TableMAT}
            position={[-98.34, 87.325, 195.465]}
          />
          <mesh
            geometry={nodes.Vase_VaseMAT_0.geometry}
            material={materials.VaseMAT}
            position={[29.978, -0.646, 17.642]}
            rotation={[-0.003, -0.163, 0]}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/hallway.gltf');

export default Hallway;
