/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 horus.glb 
Author: Seyquil (https://sketchfab.com/Leyde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/thorus-fbcbdd7ac10e4763991caf28c2074065
Title: Thorus
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Horus = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/horus.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="Object_11"
            geometry={nodes.Object_11.geometry}
            material={materials.Siamois_low_weapon_default2}
            skeleton={nodes.Object_11.skeleton}
            scale={0.015}
          />
          <skinnedMesh
            name="Object_13"
            geometry={nodes.Object_13.geometry}
            material={materials.Siamois_low_weapon_default2}
            skeleton={nodes.Object_13.skeleton}
            scale={0.015}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/horus.glb');

export default Horus;
