/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 horus.gltf 
Author: Seyquil (https://sketchfab.com/Leyde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/thorus-fbcbdd7ac10e4763991caf28c2074065
Title: Thorus
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Horus = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/horus.gltf');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.015}
          >
            <group
              name="26f2310896ca42dfb0ad3a10c5893ec0fbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group name="siamois_geo" position={[0, 2.541, 0]}>
                    <group name="body" />
                    <group
                      name="weapon"
                      position={[1.319, 88.476, -77.759]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group name="Character1_Reference">
                    <group name="Object_8">
                      <primitive object={nodes._rootJoint} />
                      <group name="Object_10" position={[0, 2.541, 0]} />
                      <group
                        name="Object_12"
                        position={[1.319, 91.017, -77.759]}
                        rotation={[Math.PI / 2, 0, 0]}
                      />
                      <skinnedMesh
                        name="Object_11"
                        geometry={nodes.Object_11.geometry}
                        material={materials.Siamois_low_weapon_default2}
                        skeleton={nodes.Object_11.skeleton}
                      />
                      <skinnedMesh
                        name="Object_13"
                        geometry={nodes.Object_13.geometry}
                        material={materials.Siamois_low_weapon_default2}
                        skeleton={nodes.Object_13.skeleton}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/horus.gltf');

export default Horus;
