/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone.glb 
Author: MajdyModels (https://sketchfab.com/MG990)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-pro-max-41a071ae12794b668502f58d1e0fd1a3
Title: iPhone 16 Pro Max
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

const Iphone = (props) => {
  const { nodes, materials } = useGLTF('/iphone.glb');
  const ref = useRef();

  useFloating(ref);

  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Circle010_black002_0.geometry}
          material={materials.PaletteMaterial001}
          position={[0.016, 0.022, 0.001]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={0.842}
        />
        <mesh
          geometry={nodes.Cube014_metalframe002_0.geometry}
          material={materials['metalframe.002']}
          position={[0.017, 0.023, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.842}
        />
        <mesh
          geometry={nodes.Cube014_glass002_0.geometry}
          material={materials.PaletteMaterial002}
          position={[0.019, 0.023, 0.001]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.832}
        />
        <mesh
          geometry={nodes.Cube014_screen001_0.geometry}
          material={materials['screen.001']}
          position={[-0.047, 0.023, 0.001]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.832}
        />
        <mesh
          geometry={nodes.Cylinder021_Material_0.geometry}
          material={materials.Material}
          position={[0.056, 0.759, 0.068]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.032}
        />
        <mesh
          geometry={nodes.Sphere010_lensinglass_0.geometry}
          material={materials.PaletteMaterial003}
          position={[0.018, 0.648, 0.156]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.066, 0.15, 0.15]}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/iphone.glb');

export default Iphone;
