/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 knight.gltf 
Author: illustros (https://sketchfab.com/illustros)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/medieval-knight-ed2e19900a7942289a2624cfef16bb4e
Title: Medieval Knight
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Knight = (props) => {
  const { nodes, materials } = useGLTF('/knight.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={
            materials['tripo_material_96cbe564-4d16-4a97-96b6-0835aa130e7d']
          }
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={
            materials['tripo_material_96cbe564-4d16-4a97-96b6-0835aa130e7d']
          }
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/knight.gltf');

export default Knight;
