/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lamp.gltf 
Author: Khabib (https://sketchfab.com/KhabibEGO)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gas-lamp-0a5013605cc848e89ae5b2e3396504da
Title: Gas Lamp
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Lamp = (props) => {
  const { nodes, materials } = useGLTF('/lamp.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group scale={0.01}>
          <mesh
            geometry={nodes['1_Material_0'].geometry}
            material={materials.Material}
            position={[0.256, 57.302, -0.239]}
            rotation={[-1.567, -0.003, -0.01]}
            scale={100}
          />
          <mesh
            geometry={nodes['5_Material011_0'].geometry}
            material={materials['Material.011']}
            position={[0.156, 95.705, -0.088]}
            rotation={[-1.567, -0.003, -0.01]}
            scale={109.501}
          />
          <mesh
            geometry={nodes['3_Material_0'].geometry}
            material={materials.Material}
            position={[-0.155, 215.729, 0.381]}
            rotation={[-1.567, -0.003, -0.01]}
            scale={[125.157, 125.157, 107.705]}
          />
          <mesh
            geometry={nodes['4_Material_0'].geometry}
            material={materials.Material}
            position={[-0.296, 270.109, 0.594]}
            rotation={[-1.567, -0.003, -0.01]}
            scale={[125.157, 125.157, 107.705]}
          />
          <mesh
            geometry={nodes['2_Material_0'].geometry}
            material={materials.Material}
            position={[-88.153, 241.566, -0.41]}
            rotation={[-1.567, -0.003, -0.01]}
            scale={100}
          />
          <mesh
            geometry={nodes['6_Material_0'].geometry}
            material={materials.Material}
            position={[0.256, 57.302, -0.239]}
            rotation={[-1.567, -0.003, -0.01]}
            scale={[33.271, 33.271, 33.513]}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/lamp.gltf');

export default Lamp;
