/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 miami.glb 
Author: Home Design 3D (https://sketchfab.com/homedesign3d)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/a-dream-in-miami-742f6d43c1e34c0a9445f7879a83126a
Title: A dream in Miami
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Miami = (props) => {
  const { nodes, materials } = useGLTF('/miami.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['20200414-205925-mesz']}
          position={[-9.256, 6.378, 9.512]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={28.278}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials['20200414-205958-mesz']}
          position={[3.744, 3.206, -1.284]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={7.528}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials['20200414-21020-mesz']}
          position={[-12.687, 2.244, -5.864]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.529}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials['20200414-2104-mesz_Wall_Entity_Material']}
          position={[-7.825, 4, 31.012]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.786}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['20200414-21118-mesz_Room_Entity_Material']}
          position={[-18.512, 6.5, -25.061]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={6.324}
        />
        <mesh
          geometry={nodes.Object_117.geometry}
          material={
            materials['screenshot_20200327-145041_chrome_Room_Entity_Material']
          }
          position={[-18.512, 1.75, -25.061]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={6.324}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials['20200414-21125-mesz_Room_Entity_Material']}
          position={[-20.106, 6.5, -12.522]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={6.215}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials['20200414-2113-mesz']}
          position={[-2.861, 4.904, 10.494]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={16.733}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials['20200414-21144-mesz']}
          position={[-8.468, 4.572, 4.676]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={36.083}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials['20200414-21234-mesz']}
          position={[-4.158, 6.374, -3.684]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={41.289}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials['20200414-21238-mesz_Room_Entity_Material']}
          position={[-12.704, 1.75, -1.215]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={5.092}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials['20200414-21248-mesz_Wall_Entity_Material']}
          position={[-3.253, 5.375, 9.531]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={28.268}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials['20200414-2125-mesz_Room_Entity_Material']}
          position={[-8.686, 6.5, -29.133]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={3.355}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials['20200517-144715-mesz_Wall_Entity_Material']}
          position={[-2.408, 4, -16.589]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.25}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials['20200517-144733-mesz_Wall_Entity_Material']}
          position={[-12.704, 8.75, 16.245]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={4.874}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials['20200517-14476-mesz']}
          position={[3.228, 4.022, 10.851]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={17.228}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.allee_de_roses___allee_de_roses_fleur}
          position={[-41.443, 0.132, -6.66]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={40.876}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.allee_de_roses___allee_de_roses_fleur_avec_tige}
          position={[-41.509, 0.15, -6.698]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={40.843}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.allee_de_roses___allee_de_roses_petale}
          position={[-41.457, 0.141, -6.676]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={40.843}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.bamboo___bamboo_feuille}
          position={[-25.558, 4.889, 14.008]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={26.862}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.PaletteMaterial001}
          position={[-6.743, 5.434, 1.462]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={51.903}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.buisson___buisson_branche_texture}
          position={[-10.964, 0.689, 2.42]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.539}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.canisse_001_Wall_Entity_Material}
          position={[-8.733, 8.75, -29.086]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={3.308}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.carrelage_013}
          position={[-2.126, 4.125, -32.297]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={13.561}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.daisies___daisiesdaisies_fleur}
          position={[-40.213, 0.335, 0.952]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={47.203}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.daisies___daisiesmaterial__554}
          position={[-40.132, 0.343, 1.012]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={47.055}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.drap_Wall_Entity_Material}
          position={[4.251, 8.75, 22.238]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={5.793}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.enduit_004_Room_Entity_Material}
          position={[5.511, 5.375, 0.136]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.964}
        />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.escalier_2m70_beton_004___mat_enduit051_2sg}
          position={[-8.897, 1.43, 0.195]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.993}
        />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.escalier_2m70_beton_004___mat_enduit_plafondsg}
          position={[-8.901, 1.182, 0.195]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.993}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.escalier_2m70_bois_006___mat_bois018sg}
          position={[-4.327, 4.142, 30.755]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.392}
        />
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials.escalier_2m70_bois_006___mat_bois102sg}
          position={[-4.325, 4.224, 30.752]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.244}
        />
        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials.PaletteMaterial002}
          position={[0.132, 5.588, -4.296]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={42.128}
        />
        <mesh
          geometry={nodes.Object_91.geometry}
          material={
            materials.foyer_exterieur_rond___foyer_exterieur_rond_foyer_exterieur_rond_grille
          }
          position={[-9.447, 6.919, -28.246]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.457}
        />
        <mesh
          geometry={nodes.Object_92.geometry}
          material={materials.foyer_exterieur_rond___phong1sg}
          position={[-9.472, 6.888, -28.221]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.278}
        />
        <mesh
          geometry={nodes.Object_94.geometry}
          material={materials.ground_herbe_1_Room_Entity_Material}
          position={[-9.624, 1.75, 0.136]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.964}
        />
        <mesh
          geometry={nodes.Object_96.geometry}
          material={materials.mur_vegetal_off___phong150}
          position={[10.399, 4.304, -38.662]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={7.092}
        />
        <mesh
          geometry={nodes.Object_97.geometry}
          material={materials.mur_vegetal_off___phong151}
          position={[10.293, 4.289, -38.595]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={7.053}
        />
        <mesh
          geometry={nodes.Object_98.geometry}
          material={materials.mur_vegetal_off___phong31}
          position={[10.312, 4.245, -39.26]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={7.247}
        />
        <mesh
          geometry={nodes.Object_99.geometry}
          material={materials.pack_003_salon_plante___material__144}
          position={[-20.69, 4.856, -7.487]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={36.7}
        />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={materials.pack_003_salon_television___material__80_1}
          position={[-3.531, 6.51, -1.479]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={38.761}
        />
        <mesh
          geometry={nodes.Object_101.geometry}
          material={materials.parquet_022_Room_Entity_Material}
          position={[-9.624, 3.25, 0.136]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.864}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.plante_interieur_off___phong80}
          position={[-20.643, 2.98, -29.435]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.229}
        />
        <mesh
          geometry={nodes.Object_103.geometry}
          material={materials.plante_vase_off_001___phong37}
          position={[-5.933, 4.823, -6.758]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={36.531}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.plante_vase_off_002___phong38}
          position={[-10.593, 4.993, 2.399]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={25.909}
        />
        <mesh
          geometry={nodes.Object_105.geometry}
          material={materials.plante_vase_off_003___phong39}
          position={[-20.236, 4.865, 27.929]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.233}
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials['screenshot_20200326-150933_chrome']}
          position={[-3.414, 4.135, 1.17]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={32.629}
        />
        <mesh
          geometry={nodes.Object_109.geometry}
          material={
            materials['screenshot_20200326-154941_chrome_Wall_Entity_Material']
          }
          position={[-12.704, 4, 16.445]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={4.873}
        />
        <mesh
          geometry={nodes.Object_110.geometry}
          material={
            materials['screenshot_20200326-155235_chrome_Room_Entity_Material']
          }
          position={[-0.138, 1.75, -38.873]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={10.991}
        />
        <mesh
          geometry={nodes.Object_111.geometry}
          material={
            materials['screenshot_20200326-155355_chrome_Wall_Entity_Material']
          }
          position={[-9.624, 5.375, 0.136]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={49.964}
        />
        <mesh
          geometry={nodes.Object_115.geometry}
          material={
            materials['screenshot_20200326-155419_chrome_Room_Entity_Material']
          }
          position={[-9.911, 6.25, -25.061]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={6.324}
        />
        <mesh
          geometry={nodes.Object_116.geometry}
          material={materials['screenshot_20200326-203458_chrome']}
          position={[-6.855, 4.544, -7.652]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={35.044}
        />
        <mesh
          geometry={nodes.Object_118.geometry}
          material={
            materials[
              'screenshot_20200327-145810_chrome_ovcole6e6e6colpic12contpic04_Wall_Entity_Material'
            ]
          }
          position={[-0.098, 4, -38.873]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={10.931}
        />
        <mesh
          geometry={nodes.Object_119.geometry}
          material={materials['screenshot_20200327-150719_chrome']}
          position={[-2.949, 5.097, -11.266]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={35.261}
        />
        <mesh
          geometry={nodes.Object_120.geometry}
          material={materials.spa_luxe___phong1sg}
          position={[-18.257, 5.5, -2.517]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={43.178}
        />
        <mesh
          geometry={nodes.Object_121.geometry}
          material={materials.spa_luxe___spa_luxespa_luxe_jets}
          position={[-20.685, 2.442, -25.345]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.281}
        />
        <mesh
          geometry={nodes.Object_127.geometry}
          material={materials.vase_fleur_off___phong94}
          position={[-20.592, 4.76, 27.87]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.248}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/miami.glb');

export default Miami;
