/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 nuclear.gltf 
Author: FWTeastwood (https://sketchfab.com/FWTeastwood)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nuclear-bomb-983f0611b6c54a329b09f3383d26d18a
Title: Nuclear Bomb
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Nuclear = (props) => {
  const { nodes, materials } = useGLTF('/nuclear.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.blinn1SG}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.blinn1SG}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/nuclear.gltf');

export default Nuclear;
