/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pacman.gltf 
Author: subtixx (https://sketchfab.com/subtixx)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pacman-17800bd2ae224ee281e43efcbc498e43
Title: PacMan
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Pacman = (props) => {
  const { nodes, materials } = useGLTF('/pacman.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group position={[0, -1.996, 0.075]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object002_Object002_mtl_0.geometry}
            material={materials.Object002_mtl}
            position={[0, 0.075, 1.996]}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/pacman.gltf');

export default Pacman;
