/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pharaon.gltf 
Author: Luis 3D (https://sketchfab.com/luism3D)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/ramses-ii-egyptian-statue-louvre-94de28f4890e4cfab99fad8c31c72bae
Title: Ramsès II Egyptian statue - Louvre
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Pharaon = (props) => {
  const { nodes, materials } = useGLTF('/pharaon.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.main}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/pharaon.gltf');

export default Pharaon;
