/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 poly.glb 
Author: PublicAudiovisual_XR (https://sketchfab.com/Jordi_Martos77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/terrain-low-poly-248b21331315466e98d20c441935d99d
Title: Terrain Low Poly
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Poly = (props) => {
  const { nodes, materials } = useGLTF('/poly.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.594, 13.805, 0.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={28.989}
        />
        <instancedMesh
          args={[nodes.Object_3.geometry, materials.PaletteMaterial001, 17]}
          instanceMatrix={nodes.Object_3.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Object_4.geometry, materials.PaletteMaterial001, 17]}
          instanceMatrix={nodes.Object_4.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Object_35.geometry, materials.PaletteMaterial001, 14]}
          instanceMatrix={nodes.Object_35.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.Object_36.geometry, materials.PaletteMaterial001, 14]}
          instanceMatrix={nodes.Object_36.instanceMatrix}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/poly.glb');

export default Poly;
