/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 poly.gltf 
Author: PublicAudiovisual_XR (https://sketchfab.com/Jordi_Martos77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/terrain-low-poly-248b21331315466e98d20c441935d99d
Title: Terrain Low Poly
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Poly = (props) => {
  const { nodes, materials } = useGLTF('/poly.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.035}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[189.196, 818.955, -230.9]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[16.648, 818.955, -559.82]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[129.883, 818.955, -629.918]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[324, 818.955, -791.682]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_21.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[324, 870.56, -516.683]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_23.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-269.135, 857.659, -500.507]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_27.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-225.997, 818.955, -575.997]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_29.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-1002.464, 818.955, -1131.386]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-824.524, 818.955, -1400.992]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-166.684, 818.955, -802.466]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-393.154, 806.054, -495.115]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-695.113, 818.955, -381.88]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-873.053, 818.955, -403.448]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-883.837, 818.955, -716.192]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-598.054, 818.955, -678.447]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-161.292, 864.109, -403.448]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[-21.64, 1942.755, 1937.444]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_59.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_60.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-188.796, 1942.755, 2126.169]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_62.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-728.009, 1942.755, 1716.367]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_65.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_66.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-706.441, 1942.755, 1921.268]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_68.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_69.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-1078.498, 1942.755, 1506.074]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_71.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_72.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-0.072, 1942.755, 1748.72]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_74.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_75.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-711.833, 1942.755, 1527.642]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_77.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_78.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-922.126, 1942.755, 1311.957]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_80.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_81.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-765.754, 1942.755, 934.508]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_83.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_84.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-296.639, 1969.633, 1554.603]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_86.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_87.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-873.597, 1958.882, 2115.385]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_89.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_90.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-506.932, 1996.51, 1818.817]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_92.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_93.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-884.381, 1985.759, 1802.641]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_95.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_96.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-409.874, 1942.755, 2244.795]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_98.geometry}
              material={materials.Leaves2}
            />
            <mesh
              geometry={nodes.Object_99.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group
            position={[-393.154, 818.955, -144.626]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_101.geometry}
              material={materials.Brown}
            />
            <mesh
              geometry={nodes.Object_102.geometry}
              material={materials.Leaves}
            />
          </group>
          <group
            position={[1.793, 25.393, -7.173]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Object_104.geometry}
              material={materials.Ground}
            />
            <mesh
              geometry={nodes.Object_105.geometry}
              material={materials.Montaña}
            />
            <mesh
              geometry={nodes.Object_106.geometry}
              material={materials.Snow}
            />
          </group>
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.Clouds}
            position={[187.196, 902.776, 53.825]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.Clouds}
            position={[163.902, 741.11, -852.448]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.Clouds}
            position={[-278.684, 803.227, -495.273]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/poly.gltf');

export default Poly;
