/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 portal.gltf 
Author: Kroko.blend (https://sketchfab.com/jaromir.ternavskiy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/portal-door-46983acd0eac4fd4a9bb206b1df029ba
Title: Portal Door
*/

import React, { useRef } from 'react';
import { Center, useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';
// import useFloating from '@/lib/useFloating';

const Portal = (props) => {
  const { nodes, materials } = useGLTF('/portal.gltf');
  const ref = useRef();

  // useFloating(ref);

  return (
    <Center position={[0, 1, 0]}>
      <group ref={ref} {...props} dispose={null}>
        <lOD>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials['Material.001']}
            position={[5.605, 1.947, -0.331]}
            rotation={[0, 0.071, 0]}
            scale={[0.677, 1, 0.729]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials['Material.001']}
            position={[0.534, 1.947, 0.029]}
            rotation={[0, 0.071, 0]}
            scale={[-0.738, 1, 0.729]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.Material}
            position={[3.122, 5.267, -0.303]}
            rotation={[0, 0.03, -Math.PI]}
            scale={[1.005, 1, 0.883]}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials['Material.002']}
            position={[3.165, 3.524, 0.561]}
            rotation={[0, 0.027, 0]}
            scale={[2.373, 2.596, 1.163]}
          />
        </lOD>
      </group>
    </Center>
  );
};

useGLTF.preload('/portal.gltf');

export default Portal;
