/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pteranodon.gltf 
Author: mike69420 (https://sketchfab.com/mike69420)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pteranodon-0f4134c1b09746069f7bbac26b4c827b
Title: Pteranodon
*/

import React from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Pteranodon = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/pteranodon.gltf');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={246.552}
          >
            <group
              name="0e3f0d87f2c1425ca0ce55f91a21f2d3fbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group name="Shell_001">
                    <group name="Pet" position={[-0.905, 1.279, -0.485]}>
                      <group name="Pteranodon(LP)" scale={0.05}>
                        <group name="Object_7">
                          <primitive object={nodes._rootJoint} />
                          <group
                            name="Object_9"
                            position={[-0.905, 1.279, -0.485]}
                            scale={0.05}
                          />
                          <group name="ptera_LOD_2" />
                          <skinnedMesh
                            name="Object_10"
                            geometry={nodes.Object_10.geometry}
                            material={materials.pteraLowPoly}
                            skeleton={nodes.Object_10.skeleton}
                          />
                          <skinnedMesh
                            name="Object_11"
                            geometry={nodes.Object_11.geometry}
                            material={materials.eyes}
                            skeleton={nodes.Object_11.skeleton}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/pteranodon.gltf');

export default Pteranodon;
