/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pteranodon.glb 
Author: mike69420 (https://sketchfab.com/mike69420)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pteranodon-0f4134c1b09746069f7bbac26b4c827b
Title: Pteranodon
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Pteranodon = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/pteranodon.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="Object_10"
            geometry={nodes.Object_10.geometry}
            material={materials.pteraLowPoly}
            skeleton={nodes.Object_10.skeleton}
            position={[-2.231, 3.153, -1.196]}
            scale={0.123}
          />
          <skinnedMesh
            name="Object_11"
            geometry={nodes.Object_11.geometry}
            material={materials.eyes}
            skeleton={nodes.Object_11.skeleton}
            position={[-2.231, 3.153, -1.196]}
            scale={0.123}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/pteranodon.glb');

export default Pteranodon;
