/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pyramid.gltf 
Author: MarloesB (https://sketchfab.com/MarloesB)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pyramid-2e0a99016e5a4ac5a9b56caf6a802b06
Title: Pyramid
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Pyramid = (props) => {
  const { nodes, materials } = useGLTF('/pyramid.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.pCube1_lambert2_0.geometry}
          material={materials.lambert2}
          scale={4.875}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/pyramid.gltf');

export default Pyramid;
