/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rubik.glb 
Author: DoobiDooba (https://sketchfab.com/DoobiDooba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-155420e09a124ec3a3bcca0852280672
Title: rubik's cube
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Rubik = (props) => {
  const { nodes, materials } = useGLTF('/rubik.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.RubixCube_RubixCube_0.geometry}
          material={materials.RubixCube}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.063}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/rubik.glb');

export default Rubik;
