/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rubik.gltf 
Author: DoobiDooba (https://sketchfab.com/DoobiDooba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-155420e09a124ec3a3bcca0852280672
Title: rubik's cube
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Rubik = (props) => {
  const { nodes, materials } = useGLTF('/rubik.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={1.154}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.RubixCube_RubixCube_0.geometry}
              material={materials.RubixCube}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/rubik.gltf');

export default Rubik;
