/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sphinx.glb 
Author: Sofia Nasopoulou (https://sketchfab.com/sofianasopoulou)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/egyptian-style-sphinx-statue-9003a8376d7444bfb435391333116ef7
Title: Egyptian-style sphinx statue
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Sphinx = (props) => {
  const { nodes, materials } = useGLTF('/sphinx.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Textured_mesh_1}
          position={[3.495, -8.056, 1.128]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
          scale={14.461}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/sphinx.glb');

export default Sphinx;
