/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stonehead.glb 
Author: VidovicArts (https://sketchfab.com/oshjavid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/easter-island-head-63b114c5e7d24f7fae421dfacfe41376
Title: Easter island head
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

export function StoneHead(props) {
  const { nodes, materials } = useGLTF('/stonehead.glb');
  const ref = useRef();

  useFloating(ref);

  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Scene_-_Root']}
          position={[-0.185, 65.212, 6.323]}
          rotation={[-Math.PI / 2, -0.006, 0]}
          scale={105.222}
        />
      </lOD>
    </group>
  );
}

useGLTF.preload('/stonehead.glb');
export default StoneHead;
