/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stonehead.gltf 
Author: VidovicArts (https://sketchfab.com/oshjavid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/easter-island-head-63b114c5e7d24f7fae421dfacfe41376
Title: Easter island head
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

const StoneHead = (props) => {
  const { nodes, materials } = useGLTF('/stonehead.gltf');
  const ref = useRef();

  useFloating(ref);

  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Scene_-_Root']}
          position={[0.397, 0.002, 0]}
          rotation={[-Math.PI / 2, -0.006, 0]}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/stonehead.gltf');

export default StoneHead;
