/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sword.glb 
Author: LowSeb (https://sketchfab.com/lowseb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-sword-da574cba504e4b83a3293f3d3bd067fb
Title: medieval sword
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import useFloating from '@/lib/hooks/useFloating';

const Sword = (props) => {
  const { nodes, materials } = useGLTF('/sword.glb');
  const ref = useRef();

  useFloating(ref);
  return (
    <group ref={ref} {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.wire_135059008}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/sword.glb');

export default Sword;
