/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 temple.gltf 
Author: BenVanhaelst (https://sketchfab.com/BenVanhaelst)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-egyptian-embalmer-6baf039826e242a69dbb44d643b84002
Title: Stylized Egyptian Embalmer
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Temple = (props) => {
  const { nodes, materials } = useGLTF('/temple.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group position={[0, 2.018, -0.737]} rotation={[-1.564, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.polySurface4038_Building_0.geometry}
              material={materials.Building}
            />
            <mesh
              geometry={nodes.polySurface4038_folliage_0.geometry}
              material={materials.folliage}
            />
            <mesh
              geometry={nodes.polySurface4038_Fires_0.geometry}
              material={materials.Fires}
            />
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/temple.gltf');

export default Temple;
