/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 temple.glb 
Author: BenVanhaelst (https://sketchfab.com/BenVanhaelst)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-egyptian-embalmer-6baf039826e242a69dbb44d643b84002
Title: Stylized Egyptian Embalmer
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Temple = (props) => {
  const { nodes, materials } = useGLTF('/temple.glb');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <mesh
          geometry={nodes.polySurface4038_Building_0.geometry}
          material={materials.Building}
          position={[282.376, 104.312, 284.3]}
          rotation={[0.007, 0, 0]}
          scale={126.739}
        />
        <mesh
          geometry={nodes.polySurface4038_folliage_0.geometry}
          material={materials.folliage}
          position={[276.866, 125.79, 277.853]}
          rotation={[0.007, 0, 0]}
          scale={146.632}
        />
        <mesh
          geometry={nodes.polySurface4038_Fires_0.geometry}
          material={materials.Fires}
          position={[292.921, 88.589, 261.275]}
          rotation={[0.007, 0, 0]}
          scale={75.522}
        />
      </lOD>
    </group>
  );
};

useGLTF.preload('/temple.glb');

export default Temple;
