/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tetris.glb 
Author: Okada (https://sketchfab.com/ToxicMind)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tetris-animation-32168c9878144bcb8ddac0930c134035
Title: Tetris Animation
*/

import React, { useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

const Tetris = (props) => {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/tetris.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group name="RootNode" scale={0.001}>
            <group
              name="pCube8"
              position={[-30, 45, 0]}
              rotation={[0, 0, Math.PI / 2]}
              scale={10}
            >
              <mesh
                name="pCube8_Flipped_Z_0"
                geometry={nodes.pCube8_Flipped_Z_0.geometry}
                material={materials.Flipped_Z}
                scale={1.5}
              />
            </group>
            <group name="pCube10" position={[35, 120, 0]} scale={10}>
              <mesh
                name="pCube10_Straight_0"
                geometry={nodes.pCube10_Straight_0.geometry}
                material={materials.Straight}
                scale={2}
              />
            </group>
          </group>
          <mesh
            name="pCube1_L_0"
            geometry={nodes.pCube1_L_0.geometry}
            material={materials.material}
            position={[-0.03, 0.025, 0]}
            scale={0.015}
          />
          <mesh
            name="pCube2_T_0"
            geometry={nodes.pCube2_T_0.geometry}
            material={materials.material_1}
            position={[-0.005, 0.02, 0]}
            scale={0.015}
          />
          <mesh
            name="pCube4_lambert8_0"
            geometry={nodes.pCube4_lambert8_0.geometry}
            material={materials.lambert8}
            position={[0, 0.035, 0]}
            scale={0.05}
          />
          <mesh
            name="pCube5_Square_0"
            geometry={nodes.pCube5_Square_0.geometry}
            material={materials.Square}
            position={[0, 0.04, 0]}
            scale={0.01}
          />
          <mesh
            name="pCube6_Straight_0"
            geometry={nodes.pCube6_Straight_0.geometry}
            material={materials.Straight}
            position={[0.025, 0.04, 0]}
            scale={0.02}
          />
          <mesh
            name="pCube7_Flipped_L_0"
            geometry={nodes.pCube7_Flipped_L_0.geometry}
            material={materials.Flipped_L}
            position={[-0.02, 0.035, 0]}
            scale={0.015}
          />
          <mesh
            name="pCube9_Z_0"
            geometry={nodes.pCube9_Z_0.geometry}
            material={materials.material_7}
            position={[0.015, 0.02, 0]}
            scale={0.015}
          />
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/tetris.glb');

export default Tetris;
