/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 train.gltf 
Author: andysedano (https://sketchfab.com/andysedano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/train-f5fa509073504c43b139e80ab62b6d11
Title: Train
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

const Train = (props) => {
  const { nodes, materials } = useGLTF('/train.gltf');
  return (
    <group {...props} dispose={null}>
      <lOD>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={4.719}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.defaultMaterial.geometry}
              material={materials.lambert8SG}
            />
            <mesh
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.lambert6SG}
            />
            <mesh
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.lambert7SG}
            />
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/train.gltf');

export default Train;
