/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ufo.gltf 
Author: yanix (https://sketchfab.com/yanix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-2d55eec1da344c9a9943abafbd07f0f9
Title: Ufo
*/

import React from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useRef } from 'react';
import useFloating from '@/lib/hooks/useFloating';

const Ufo = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/ufo.gltf');
  const { actions } = useAnimations(animations, group);

  useFloating(group);

  return (
    <group ref={group} {...props} dispose={null}>
      <lOD>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Root">
              <group name="Cube" position={[0, 0, 0.513]}>
                <mesh
                  name="Cube_0"
                  geometry={nodes.Cube_0.geometry}
                  material={materials['Material-material']}
                />
              </group>
            </group>
          </group>
        </group>
      </lOD>
    </group>
  );
};

useGLTF.preload('/ufo.gltf');

export default Ufo;
