import type { Metadata } from 'next';
import { Genos } from 'next/font/google';
import './globals.css';

const genosSans = Genos({
  variable: '--font-genos-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${genosSans.variable} dark antialiased`}>
        {children}
      </body>
    </html>
  );
}
